<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Produk;

class ProdukSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'id_produk' => 'PRD001',
                'id_kategori' => 1,
                'nama_produk' => 'Kemeja pendek bayi',
                'deskripsi' => 'Kemeja bayi lengan pendek berbahan katun lembut',
                'image_url' => '/img/kategori/kemeja1.png',
                'harga' => 200000.00,
                'stock' => 50,
            ],
            [
                'id_produk' => 'PRD002',
                'id_kategori' => 2,
                'nama_produk' => 'Kaos bayi set',
                'deskripsi' => 'Set kaos bayi dengan motif lucu',
                'image_url' => '/img/kategori/kaosset.png',
                'harga' => 200000.00,
                'stock' => 60,
            ],
            [
                'id_produk' => 'PRD003',
                'id_kategori' => 3,
                'nama_produk' => 'set polo + sepatu',
                'deskripsi' => 'Set polo bayi dengan sepatu yang matching',
                'image_url' => '/img/kategori/image18.png',
                'harga' => 900000.00,
                'stock' => 30,
            ],
            [
                'id_produk' => 'PRD004',
                'id_kategori' => 4,
                'nama_produk' => 'Tshirt bayi',
                'deskripsi' => 'Tshirt lucu dan nyaman untuk bayi',
                'image_url' => '/img/kategori/setkaos.png',
                'harga' => 90000.00,
                'stock' => 40,
            ],
            [
                'id_produk' => 'PRD005',
                'id_kategori' => 5,
                'nama_produk' => 'Kemeja panda + celana',
                'deskripsi' => 'Kemeja panda untuk bayi dengan celana matching',
                'image_url' => '/img/kategori/kemejaputih.png',
                'harga' => 500000.00,
                'stock' => 25,
            ],
            [
                'id_produk' => 'PRD006',
                'id_kategori' => 6,
                'nama_produk' => 'jaket polos',
                'deskripsi' => 'Jaket bayi polos untuk udara dingin',
                'image_url' => '/img/kategori/jaket.png',
                'harga' => 200000.00,
                'stock' => 30,
            ],
            [
                'id_produk' => 'PRD007',
                'id_kategori' => 7,
                'nama_produk' => 'Jaket motif crown',
                'deskripsi' => 'Jaket bayi dengan motif crown yang lucu',
                'image_url' => '/img/kategori/image.png',
                'harga' => 250000.00,
                'stock' => 35,
            ],
            [
                'id_produk' => 'PRD008',
                'id_kategori' => 8,
                'nama_produk' => 'Set vest + jaket + celana',
                'deskripsi' => 'Set pakaian bayi dengan vest, jaket, dan celana yang matching',
                'image_url' => '/img/kategori/image1.png',
                'harga' => 1000000.00,
                'stock' => 10,
            ],
            [
                'id_produk' => 'PRD009',
                'id_kategori' => 9,
                'nama_produk' => 'Set singlet motif dino',
                'deskripsi' => 'Set pakaian bayi dengan singlet motif dino',
                'image_url' => '/img/kategori/image2.png',
                'harga' => 200000.00,
                'stock' => 10,
            ],
            [
                'id_produk' => 'PRD0010',
                'id_kategori' => 10,
                'nama_produk' => 'Kaos garis + celana',
                'deskripsi' => 'Kaos bayi dengan motif garis dan celana matching',
                'image_url' => '/img/kategori/image3.png',
                'harga' => 200000.00,
                'stock' => 10,
            ],
            [
                'id_produk' => 'PRD0011',
                'id_kategori' => 11,
                'nama_produk' => 'polo polos bayi',
                'deskripsi' => 'polo polos bayi dengan bahan katun lembut',
                'image_url' => '/img/kategori/image4.png',
                'harga' => 200000.00,
                'stock' => 50,
            ],
            [
                'id_produk' => 'PRD0012',
                'id_kategori' => 12,
                'nama_produk' => 'set kemeja + sepatu',
                'deskripsi' => 'Set kemeja bayi dengan sepatu matching',
                'image_url' => '/img/kategori/image5.png',
                'harga' => 1000000.00,
                'stock' => 60,
            ],
            [
                'id_produk' => 'PRD0013',
                'id_kategori' => 13,
                'nama_produk' => 'Dress bunga',
                'deskripsi' => 'Dress bayi dengan motif bunga yang cantik',
                'image_url' => '/img/kategori/dressbunga.png',
                'harga' => 500000.00,
                'stock' => 30,
            ],
            [
                'id_produk' => 'PRD0014',
                'id_kategori' => 14,
                'nama_produk' => 'Set baju + sepatu cewek',
                'deskripsi' => 'Set baju dan sepatu bayi cewek yang modis',
                'image_url' => '/img/kategori/bajusepatu.png',
                'harga' => 900000.00,
                'stock' => 40,
            ],
            [
                'id_produk' => 'PRD0015',
                'id_kategori' => 15,
                'nama_produk' => 'set kaos + vest cewek',
                'deskripsi' => 'Set kaos dan vest anak perempuan yang modis',
                'image_url' => '/img/kategori/image6.png',
                'harga' => 500000.00,
                'stock' => 25,
            ],
            [
                'id_produk' => 'PRD0016',
                'id_kategori' => 16,
                'nama_produk' => 'Tshirt cewek motif beruang',
                'deskripsi' => 'Tshirt anak perempuan dengan motif beruang yang lucu',
                'image_url' => '/img/kategori/image7.png',
                'harga' => 90000.00,
                'stock' => 15,
            ],
            [
                'id_produk' => 'PRD0017',
                'id_kategori' => 17,
                'nama_produk' => 'Dress bunga matahari',
                'deskripsi' => 'Dress anak perempuan dengan motif bunga matahari yang ceria',
                'image_url' => '/img/kategori/image8.png',
                'harga' => 900000.00,
                'stock' => 35,
            ],
            [
                'id_produk' => 'PRD0018',
                'id_kategori' => 18,
                'nama_produk' => 'Dress lebah',
                'deskripsi' => 'Dress anak perempuan dengan motif lebah yang lucu',
                'image_url' => '/img/kategori/image9.png',
                'harga' => 900000.00,
                'stock' => 10,
            ],
            [
                'id_produk' => 'PRD0019',
                'id_kategori' => 19,
                'nama_produk' => 'Fleece motif love',
                'deskripsi' => 'Fleece bayi dengan motif love yang lucu',
                'image_url' => '/img/kategori/image10.png',
                'harga' => 800000.00,
                'stock' => 10,
            ],
            [
                'id_produk' => 'PRD0020',
                'id_kategori' => 20,
                'nama_produk' => 'Varsity jacket NY',
                'deskripsi' => 'Jaket bayi dengan desain varsity NY yang stylish',
                'image_url' => '/img/kategori/ny.png',
                'harga' => 800000.00,
                'stock' => 10,
            ],
            [
                'id_produk' => 'PRD0021',
                'id_kategori' => 21,
                'nama_produk' => 'Jaket kelinci',
                'deskripsi' => 'Jaket bayi berbentuk kelinci yang lucu',
                'image_url' => '/img/kategori/jaketkelinci.png',
                'harga' => 80000.00,
                'stock' => 50,
            ],
            [
                'id_produk' => 'PRD0022',
                'id_kategori' => 22,
                'nama_produk' => 'Cardigan bayi',
                'deskripsi' => 'Cardigan bayi dengan motif lucu',
                'image_url' => '/img/kategori/cardigan.png',
                'harga' => 200000.00,
                'stock' => 60,
            ],
            [
                'id_produk' => 'PRD0023',
                'id_kategori' => 23,
                'nama_produk' => 'Set dress + rok',
                'deskripsi' => 'Set dress dan rok untuk anak perempuan',
                'image_url' => '/img/kategori/image11.png',
                'harga' => 500000.00,
                'stock' => 30,
            ],
            [
                'id_produk' => 'PRD0024',
                'id_kategori' => 24,
                'nama_produk' => 'Dress polos',
                'deskripsi' => 'Dress polos yang nyaman untuk anak perempuan',
                'image_url' => '/img/kategori/image12.png',
                'harga' => 500000.00,
                'stock' => 40,
            ],
            [
                'id_produk' => 'PRD0025',
                'id_kategori' => 25,
                'nama_produk' => 'Piyama bayi',
                'deskripsi' => 'Piyama bayi lembut',
                'image_url' => '/img/kategori/piyama1.png',
                'harga' => 150000.00,
                'stock' => 25,
            ],
            [
                'id_produk' => 'PRD0026',
                'id_kategori' => 26,
                'nama_produk' => 'Piyama bayi motif beruang',
                'deskripsi' => 'Piyama bayi dengan motif beruang yang lucu',
                'image_url' => '/img/kategori/image13.png',
                'harga' => 200000.00,
                'stock' => 15,
            ],
            [
                'id_produk' => 'PRD0027',
                'id_kategori' => 27,
                'nama_produk' => 'Piyama bayi pink',
                'deskripsi' => 'Piyama bayi berwarna pink yang lucu',
                'image_url' => '/img/kategori/pinkpink.png',
                'harga' => 150000.00,
                'stock' => 35,
            ],
            [
                'id_produk' => 'PRD0028',
                'id_kategori' => 28,
                'nama_produk' => 'Piyama bayi motif',
                'deskripsi' => 'Piyama bayi dengan motif lucu',
                'image_url' => '/img/kategori/image14.png',
                'harga' => 150000.00,
                'stock' => 10,
            ],
            [
                'id_produk' => 'PRD0029',
                'id_kategori' => 29,
                'nama_produk' => 'Piyama bayi snoopy',
                'deskripsi' => 'Piyama bayi dengan motif snoopy yang lucu',
                'image_url' => '/img/kategori/snoopy.png',
                'harga' => 250000.00,
                'stock' => 10,
            ],
            [
                'id_produk' => 'PRD0030',
                'id_kategori' => 30,
                'nama_produk' => 'Piyama motif hewan',
                'deskripsi' => 'Piyama bayi dengan motif hewan yang lucu',
                'image_url' => '/img/kategori/image15.png',
                'harga' => 250000.00,
                'stock' => 10,
            ],
            [
                'id_produk' => 'PRD0031',
                'id_kategori' => 31,
                'nama_produk' => 'Piyama motif beruang',
                'deskripsi' => 'Piyama bayi dengan motif beruang yang lucu',
                'image_url' => '/img/kategori/image16.png',
                'harga' => 250000.00,
                'stock' => 50,
            ],
            [
                'id_produk' => 'PRD0032',
                'id_kategori' => 32,
                'nama_produk' => 'Piyama motif buah pendek',
                'deskripsi' => 'Piyama bayi dengan motif buah yang lucu',
                'image_url' => '/img/kategori/buah.png',
                'harga' => 150000.00,
                'stock' => 60,
            ],
            [
                'id_produk' => 'PRD0033',
                'id_kategori' => 33,
                'nama_produk' => 'Piyama kelinci',
                'deskripsi' => 'Piyama bayi dengan motif kelinci yang lucu',
                'image_url' => '/img/kategori/piyamakelinci.png',
                'harga' => 200000.00,
                'stock' => 30,
            ],
            [
                'id_produk' => 'PRD0034',
                'id_kategori' => 34,
                'nama_produk' => 'Piyama cewek beruang',
                'deskripsi' => 'Piyama lucu motif beruang untuk anak perempuan',
                'image_url' => '/img/kategori/piyamaceweberuang.png',
                'harga' => 2000000.00,
                'stock' => 40,
            ],
            [
                'id_produk' => 'PRD0035',
                'id_kategori' => 35,
                'nama_produk' => 'Piyama sapi',
                'deskripsi' => 'Piyama bayi dengan motif sapi yang lucu',
                'image_url' => '/img/kategori/piyamasapi.png',
                'harga' => 200000.00,
                'stock' => 25,
            ],
            [
                'id_produk' => 'PRD0036',
                'id_kategori' => 36,
                'nama_produk' => 'Piyama lengan panjang motif buah',
                'deskripsi' => 'Piyama bayi lengan panjang dengan motif buah yang lucu',
                'image_url' => '/img/kategori/image17.png',
                'harga' => 200000.00,
                'stock' => 15,
            ],
        ];

        foreach ($data as $produk) {
            Produk::create($produk);
        }
    }
}
