<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Produk;

class ProdukSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            // Data produk lama (tidak diubah)
            [
                'kode_produk' => 'PRD001',
                'id_kategori' => 1,
                'nama_produk' => 'Kemeja pendek bayi',
                'deskripsi' => 'Kemeja bayi lengan pendek berbahan katun lembut',
                'image_url' => 'img/kategori/kemeja1.png',
                'harga' => 200000.00,
                'stock' => 50,
            ],
            [
                'kode_produk' => 'PRD002',
                'id_kategori' => 2,
                'nama_produk' => 'Kaos bayi set',
                'deskripsi' => 'Set kaos bayi dengan motif lucu',
                'image_url' => 'img/kategori/kaosset.png',
                'harga' => 200000.00,
                'stock' => 60,
            ],
            [
                'kode_produk' => 'PRD003',
                'id_kategori' => 3,
                'nama_produk' => 'set polo + sepatu',
                'deskripsi' => 'Set polo bayi dengan sepatu yang matching',
                'image_url' => 'img/kategori/image18.png',
                'harga' => 900000.00,
                'stock' => 30,
            ],
            [
                'kode_produk' => 'PRD004',
                'id_kategori' => 4,
                'nama_produk' => 'Tshirt bayi',
                'deskripsi' => 'Tshirt lucu dan nyaman untuk bayi',
                'image_url' => 'img/kategori/setkaos.png',
                'harga' => 90000.00,
                'stock' => 40,
            ],
            [
                'kode_produk' => 'PRD005',
                'id_kategori' => 5,
                'nama_produk' => 'Kemeja panda + celana',
                'deskripsi' => 'Kemeja panda untuk bayi dengan celana matching',
                'image_url' => 'img/kategori/kemejaputih.png',
                'harga' => 500000.00,
                'stock' => 25,
            ],
            [
                'kode_produk' => 'PRD006',
                'id_kategori' => 6,
                'nama_produk' => 'jaket polos',
                'deskripsi' => 'Jaket bayi polos untuk udara dingin',
                'image_url' => 'img/kategori/jaket.png',
                'harga' => 200000.00,
                'stock' => 30,
            ],
            [
                'kode_produk' => 'PRD007',
                'id_kategori' => 1,
                'nama_produk' => 'Jaket motif crown',
                'deskripsi' => 'Jaket bayi dengan motif crown yang lucu',
                'image_url' => 'img/kategori/image.png',
                'harga' => 250000.00,
                'stock' => 35,
            ],
            [
                'kode_produk' => 'PRD008',
                'id_kategori' => 2,
                'nama_produk' => 'Set vest + jaket + celana',
                'deskripsi' => 'Set pakaian bayi dengan vest, jaket, dan celana yang matching',
                'image_url' => 'img/kategori/image2.png',
                'harga' => 700000.00,
                'stock' => 20,
            ],
            [
                'kode_produk' => 'PRD009',
                'id_kategori' => 3,
                'nama_produk' => 'Kemeja motif army',
                'deskripsi' => 'Kemeja bayi dengan motif army yang keren',
                'image_url' => 'img/kategori/image3.png',
                'harga' => 300000.00,
                'stock' => 40,
            ],
            [
                'kode_produk' => 'PRD010',
                'id_kategori' => 4,
                'nama_produk' => 'Set kaos + celana motif',
                'deskripsi' => 'Set kaos dan celana bayi dengan motif lucu',
                'image_url' => 'img/kategori/image4.png',
                'harga' => 450000.00,
                'stock' => 30,
            ],

            // Data produk baru (pakai gambar dari Unsplash)
            [
                'kode_produk' => 'PRD011',
                'id_kategori' => 5,
                'nama_produk' => 'Baju tidur bayi',
                'deskripsi' => 'Baju tidur bayi berbahan lembut dan nyaman dipakai malam hari',
                'image_url' => null,
                'harga' => 180000.00,
                'stock' => 50,
            ],
            [
                'kode_produk' => 'PRD012',
                'id_kategori' => 6,
                'nama_produk' => 'Topi bayi lucu',
                'deskripsi' => 'Topi bayi dengan desain hewan lucu yang menggemaskan',
                'image_url' => null,
                'harga' => 75000.00,
                'stock' => 80,
            ],
            [
                'kode_produk' => 'PRD013',
                'id_kategori' => 1,
                'nama_produk' => 'Set romper bayi',
                'deskripsi' => 'Romper bayi satu set dengan warna pastel',
                'image_url' => null,
                'harga' => 220000.00,
                'stock' => 40,
            ],
            [
                'kode_produk' => 'PRD014',
                'id_kategori' => 2,
                'nama_produk' => 'Sarung tangan bayi',
                'deskripsi' => 'Sarung tangan bayi menjaga tangan tetap hangat',
                'image_url' => null,
                'harga' => 40000.00,
                'stock' => 100,
            ],
            [
                'kode_produk' => 'PRD015',
                'id_kategori' => 3,
                'nama_produk' => 'Celana panjang bayi',
                'deskripsi' => 'Celana panjang bayi dari bahan yang lentur dan adem',
                'image_url' => null,
                'harga' => 110000.00,
                'stock' => 70,
            ],
            [
                'kode_produk' => 'PRD016',
                'id_kategori' => 4,
                'nama_produk' => 'Kaos kaki bayi',
                'deskripsi' => 'Kaos kaki bayi hangat dan anti selip',
                'image_url' => null,
                'harga' => 30000.00,
                'stock' => 100,
            ],
            [
                'kode_produk' => 'PRD017',
                'id_kategori' => 5,
                'nama_produk' => 'Sweater rajut bayi',
                'deskripsi' => 'Sweater bayi rajutan halus untuk musim dingin',
                'image_url' => null,
                'harga' => 250000.00,
                'stock' => 35,
            ],
            [
                'kode_produk' => 'PRD018',
                'id_kategori' => 6,
                'nama_produk' => 'Celana pendek bayi',
                'deskripsi' => 'Celana pendek bayi untuk cuaca panas',
                'image_url' => null,
                'harga' => 90000.00,
                'stock' => 60,
            ],
            [
                'kode_produk' => 'PRD019',
                'id_kategori' => 1,
                'nama_produk' => 'Bibs lucu bayi',
                'deskripsi' => 'Bibs atau celemek bayi dengan karakter hewan lucu',
                'image_url' =>  null,
                'harga' => 40000.00,
                'stock' => 85,
            ],
            [
                'kode_produk' => 'PRD020',
                'id_kategori' => 2,
                'nama_produk' => 'Selimut bayi',
                'deskripsi' => 'Selimut lembut dan hangat untuk bayi',
                'image_url' => null,
                'harga' => 120000.00,
                'stock' => 70,
            ],
            [
                'kode_produk' => 'PRD021',
                'id_kategori' => 3,
                'nama_produk' => 'Set topi dan sarung tangan',
                'deskripsi' => 'Satu set topi dan sarung tangan hangat untuk bayi',
                'image_url' => null,
                'harga' => 95000.00,
                'stock' => 50,
            ],
            [
                'kode_produk' => 'PRD022',
                'id_kategori' => 4,
                'nama_produk' => 'Romper lucu lengan panjang',
                'deskripsi' => 'Romper bayi lengan panjang dengan desain hewan lucu',
                'image_url' =>  null,
                'harga' => 170000.00,
                'stock' => 40,
            ],
            [
                'kode_produk' => 'PRD023',
                'id_kategori' => 5,
                'nama_produk' => 'Hoodie bayi motif telinga',
                'deskripsi' => 'Hoodie bayi dengan tambahan telinga binatang di tudungnya',
                'image_url' => null,
                'harga' => 270000.00,
                'stock' => 30,
            ],
            [
                'kode_produk' => 'PRD024',
                'id_kategori' => 6,
                'nama_produk' => 'Set piyama bayi',
                'deskripsi' => 'Setelan piyama lucu untuk tidur nyenyak bayi',
                'image_url' => null,
                'harga' => 150000.00,
                'stock' => 65,
            ],
            [
                'kode_produk' => 'PRD025',
                'id_kategori' => 1,
                'nama_produk' => 'Sepatu bayi karakter',
                'deskripsi' => 'Sepatu bayi dengan karakter lucu dan nyaman dipakai',
                'image_url' => null,
                'harga' => 110000.00,
                'stock' => 45,
            ],

        ];

        foreach ($data as $item) {
            Produk::create($item);
        }
    }
}
